// benchmarks/apps/solid/src/main.tsx
import { batch, createSelector, createSignal, For, type Accessor, type Setter } from 'solid-js'
import { render } from 'solid-js/web'
import { buildData } from '../../shared/data'

/**
 * Row shape mirrors the official krausest keyed Solid implementation
 * (frameworks/keyed/solid/src/main.jsx): each row carries its own
 * `label` signal so `#update` can flip just the ten changed labels'
 * text nodes without touching row identity or DOM structure. `<For>`
 * keys by row-object reference, so as long as `update` never replaces
 * a row object (only calls its `setLabel`), reordering/select/remove
 * stay fine-grained and update never remounts a `<tr>`.
 */
interface Row {
  id: number
  label: Accessor<string>
  setLabel: Setter<string>
}

function buildRows(count: number): Row[] {
  return buildData(count).map(({ id, label }) => {
    const [get, set] = createSignal(label)
    return { id, label: get, setLabel: set }
  })
}

function App() {
  const [rows, setRows] = createSignal<Row[]>([])
  const [selected, setSelected] = createSignal<number>(0)
  const isSelected = createSelector(selected)

  const run = () => setRows(buildRows(1000))
  const runLots = () => setRows(buildRows(10000))
  const add = () => setRows((d) => [...d, ...buildRows(1000)])
  const update = () =>
    batch(() => {
      const d = rows()
      for (let i = 0; i < d.length; i += 10) d[i].setLabel((l) => l + ' !!!')
    })
  const clear = () => setRows([])
  const swapRows = () => {
    const list = rows().slice()
    if (list.length > 998) {
      const tmp = list[1]
      list[1] = list[998]
      list[998] = tmp
      setRows(list)
    }
  }
  const select = (id: number) => setSelected(id)
  const remove = (id: number) => setRows((d) => d.filter((row) => row.id !== id))

  return (
    <div id="main">
      <div class="jumbotron">
        <button id="run" onClick={run}>
          Create 1,000 rows
        </button>
        <button id="runlots" onClick={runLots}>
          Create 10,000 rows
        </button>
        <button id="add" onClick={add}>
          Append 1,000 rows
        </button>
        <button id="update" onClick={update}>
          Update every 10th row
        </button>
        <button id="clear" onClick={clear}>
          Clear
        </button>
        <button id="swaprows" onClick={swapRows}>
          Swap Rows
        </button>
      </div>
      <table class="table">
        <tbody id="tbody">
          <For each={rows()}>
            {(row) => (
              <tr class={isSelected(row.id) ? 'danger' : ''}>
                <td class="col-md-1">{row.id}</td>
                <td class="col-md-4">
                  <a class="lbl" onClick={() => select(row.id)}>
                    {row.label()}
                  </a>
                </td>
                <td class="col-md-1">
                  <a class="remove" onClick={() => remove(row.id)}>
                    x
                  </a>
                </td>
                <td class="col-md-6" />
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  )
}

render(() => <App />, document.body)
document.body.dataset.ready = '1'

// benchmarks/apps/react/src/main.tsx
/**
 * React 19 benchmark app — modeled on the official krausest
 * js-framework-benchmark `keyed/react-hooks` implementation
 * (frameworks/keyed/react-hooks/src/main.jsx): a single `useReducer` for
 * the whole list + selection, a `memo`ized `Row` with a custom equality
 * function that only checks `selected` and `item` identity, and a stable
 * `dispatch` (from `useReducer`, never changes identity) threaded straight
 * through instead of per-row `useCallback` wrappers.
 *
 * Markup follows benchmarks/CONTRACT.md exactly (button ids, `#tbody`,
 * `a.lbl` / `a.remove` classes) rather than krausest's Bootstrap markup.
 */
import { type Dispatch, memo, useEffect, useReducer } from 'react'
import { createRoot } from 'react-dom/client'
import { buildData, type RowData } from '../../shared/data.ts'

interface ListState {
  data: RowData[]
  selected: number
}

type ListAction =
  | { type: 'RUN' }
  | { type: 'RUN_LOTS' }
  | { type: 'ADD' }
  | { type: 'UPDATE' }
  | { type: 'CLEAR' }
  | { type: 'SWAP_ROWS' }
  | { type: 'REMOVE'; id: number }
  | { type: 'SELECT'; id: number }

const initialState: ListState = { data: [], selected: 0 }

function listReducer(state: ListState, action: ListAction): ListState {
  const { data, selected } = state

  switch (action.type) {
    case 'RUN':
      return { data: buildData(1000), selected: 0 }
    case 'RUN_LOTS':
      return { data: buildData(10000), selected: 0 }
    case 'ADD':
      return { data: data.concat(buildData(1000)), selected }
    case 'UPDATE': {
      const newData = data.slice(0)
      for (let i = 0; i < newData.length; i += 10) {
        const r = newData[i]
        if (r) newData[i] = { id: r.id, label: `${r.label} !!!` }
      }
      return { data: newData, selected }
    }
    case 'CLEAR':
      return { data: [], selected: 0 }
    case 'SWAP_ROWS': {
      const newData = data.slice(0)
      if (data.length > 998) {
        const d1 = newData[1]
        const d998 = newData[998]
        if (d1 && d998) {
          newData[1] = d998
          newData[998] = d1
        }
      }
      return { data: newData, selected }
    }
    case 'REMOVE': {
      const idx = data.findIndex((d) => d.id === action.id)
      return { data: [...data.slice(0, idx), ...data.slice(idx + 1)], selected }
    }
    case 'SELECT':
      return { data, selected: action.id }
    default:
      return state
  }
}

interface RowProps {
  item: RowData
  selected: boolean
  dispatch: Dispatch<ListAction>
}

const Row = memo(
  ({ selected, item, dispatch }: RowProps) => (
    <tr className={selected ? 'danger' : ''}>
      <td className="col-md-1">{item.id}</td>
      <td className="col-md-4">
        <a className="lbl" onClick={() => dispatch({ type: 'SELECT', id: item.id })}>
          {item.label}
        </a>
      </td>
      <td className="col-md-1">
        <a className="remove" onClick={() => dispatch({ type: 'REMOVE', id: item.id })}>
          x
        </a>
      </td>
      <td className="col-md-6" />
    </tr>
  ),
  (prevProps, nextProps) => prevProps.selected === nextProps.selected && prevProps.item === nextProps.item,
)

function Main() {
  const [{ data, selected }, dispatch] = useReducer(listReducer, initialState)

  useEffect(() => {
    document.body.dataset.ready = '1'
  }, [])

  return (
    <>
      <div className="jumbotron">
        <button type="button" id="run" onClick={() => dispatch({ type: 'RUN' })}>
          Create 1,000 rows
        </button>
        <button type="button" id="runlots" onClick={() => dispatch({ type: 'RUN_LOTS' })}>
          Create 10,000 rows
        </button>
        <button type="button" id="add" onClick={() => dispatch({ type: 'ADD' })}>
          Append 1,000 rows
        </button>
        <button type="button" id="update" onClick={() => dispatch({ type: 'UPDATE' })}>
          Update every 10th row
        </button>
        <button type="button" id="clear" onClick={() => dispatch({ type: 'CLEAR' })}>
          Clear
        </button>
        <button type="button" id="swaprows" onClick={() => dispatch({ type: 'SWAP_ROWS' })}>
          Swap Rows
        </button>
      </div>
      <table className="table">
        <tbody id="tbody">
          {data.map((item) => (
            <Row key={item.id} item={item} selected={selected === item.id} dispatch={dispatch} />
          ))}
        </tbody>
      </table>
    </>
  )
}

const container = document.getElementById('main')
if (!container) throw new Error('#main container not found')
createRoot(container).render(<Main />)
